### ISSUE TITLE
Add new framework kendryte-freertos-sdk.

### ISSUE THREAD

**Issue by bitsk** [sipeed/platform-kendryte210#13]
"framework-kendryte-freertos-sdk":[
        {
            "sha1": "dd92433fd8ab3caae7b0e244178304a4d82b158d",
            "system": "*",
            "url": "http://dl.sipeed.com/MAIX/platformio/dl-packages/framework-kendryte-freertos-sdk-0.7.0.tar.gz",
            "version": "0.7.0"
        }
    ],

**Comment by ivankravets** [comment]
Done!
