### ISSUE TITLE
Update kendryte-standalone-sdk to v0.5.6

### ISSUE THREAD

**Issue by bitsk** [sipeed/platform-kendryte210#16]
{
            "sha1": "8ba94f5ff87eec5e13e488d98050b5e53fab2125",
            "system": "*",
            "url": "http://dl.sipeed.com/MAIX/platformio/dl-packages/framework-kendryte-standalone-sdk-0.5.6.tar.gz",
            "version": "0.5.6"
        }，

**Comment by ivankravets** [comment]
Done! Do you plan to do any changes this week? Could we make the next release?

**Comment by bitsk** [comment]
No other changes.

**Comment by ivankravets** [comment]
@btx000 is it possible to PlatformIO listed here https://maixduino.sipeed.com/en/? As an alternative to Arduino IDE with screenshots and debugging. I'm sure developers will like it.

**Comment by bitsk** [comment]
Of course, I will add.

**Comment by ivankravets** [comment]
Thanks! v1.1.1 is out! https://github.com/sipeed/platform-kendryte210/releases/tag/v1.1.1
