### ISSUE TITLE
Topics for repository

### ISSUE THREAD

**Issue by ivankravets** [sipeed/platform-kendryte210#2]
It would be great if you add the next topics to this repository:
* `platformio`
* `platformio-platform`
* `risc-v`.

Developers will be able to list open source dev/platforms for PlatformIO. See
- https://github.com/topics/platformio-platform

You can do that on the main page of the repository via "Manage topics" button. See
![Screen Shot 2019-04-25 at 13 47 54](https://user-images.githubusercontent.com/1760209/56730467-c15b0580-6760-11e9-906d-9513c914b4d0.png)

**Comment by bitsk** [comment]
added

**Comment by ivankravets** [comment]
Thanks! Do you plan to add more changes? Currently, if you make a new release of this dev/platform, you need to ping us somewhere to re-deploy to our global registry. We will fix that with new PlatformIO Registry where everyone will be able personally to manage own dev/platforms.

**Comment by bitsk** [comment]
Thanks for your reminder, we are testing on various platforms, and we can release them after the test is passed.
