### ISSUE TITLE
Rename "kendryte210-standalone-sdk" to "kendryte-standalone-sdk"

### ISSUE THREAD

**Issue by ivankravets** [sipeed/platform-kendryte210#3]
It would be good to have unified name for Kendryte Standalone SDK => https://github.com/kendryte/kendryte-standalone-sdk

Could you rename it in these places?

- https://github.com/sipeed/platform-kendryte210/blob/master/platform.json#L22
- https://github.com/sipeed/platform-kendryte210/blob/master/platform.json#L23
- https://github.com/sipeed/platform-kendryte210/blob/master/platform.json#L24
- https://github.com/sipeed/platform-kendryte210/blob/master/platform.json#L41

**Comment by ivankravets** [comment]
@btx000 could you add me to `Collaborators` list for this repo?

**Comment by bitsk** [comment]
> @btx000 could you add me to `Collaborators` list for this repo?

Added. https://github.com/sipeed/platform-kendryte210/invitations

**Comment by ivankravets** [comment]
Thanks!
