### ISSUE TITLE
Rename title to "Kendryte K210"

### ISSUE THREAD

**Issue by ivankravets** [sipeed/platform-kendryte210#4]
Can we rename a title of dev/platform to "Kendryte K210"? I really respect your efforts but keeping platforms in a simple form will ake them to look generic. The "this platform is ported by Sipeed." will be kept in the description. So, developers can find it by "Sipeed" word.

What do you think?

See https://platformio.org/platforms

**Comment by bitsk** [comment]
i think that's OK.
