### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by ivankravets** [sipeed/platform-kendryte210#5]
Need to prepare packages `toolchain-kendryte210` and `tool-openocd-kendryte210` packages for macOS.

**Comment by bitsk** [comment]
I just added the macos toolchain and openocd.
Kfalsh upgrade to version 0.8.1 . 
Their download address is here http://dl.sipeed.com/MAIX/platformio/dl-packages/manifest.json 
I have not tested on the MAC, so I am not sure if they work properly.

**Comment by ivankravets** [comment]
I tested on my macOS. It works (compiling). Thanks!

P.S: I'm going to make 1.0.0 release and socialize it in our network. Do you plan to make any critical changes soon?

**Comment by bitsk** [comment]
No big changes, thank you very much for your work.
