### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by ivankravets** [sipeed/platform-kendryte210#6]
Sorry, I don't have rights to modify project links. Could I ask a few changes?

- On the home page of this repository specify **Website** to `https://platformio.org/platforms/kendryte210`
- Update **Description** to `Kendryte K210: development platform for PlatformIO`

We added extended information and docs on our side:
- https://platformio.org/platforms/kendryte210
- https://docs.platformio.org/en/latest/platforms/kendryte210.html

**Comment by bitsk** [comment]
You can update this information according to your ideas.

**Comment by ivankravets** [comment]
I can't. Github does not allow me :( This option is available only for repository owners.
![Screen Shot 2019-05-04 at 12 49 16](https://user-images.githubusercontent.com/1760209/57177239-0a027500-6e6b-11e9-8e0a-9392e48263c4.png)

**Comment by bitsk** [comment]
Sorry, I just understood that there is something wrong. It has changed now.

**Comment by ivankravets** [comment]
Thanks!
