### ISSUE TITLE
Update kflash to v0.8.2

### ISSUE THREAD

**Issue by bitsk** [sipeed/platform-kendryte210#8]
There is a serious bug in the kflash v0.8.1 version, and the new version has been fixed.
``` 
       {
            "sha1": "afd2123d6574049d2dae6c0f0cbab040ad1fdfc7",
            "system": "*",
            "url": "http://dl.sipeed.com/MAIX/platformio/dl-packages/tool-kflash-kendryte210-v0.8.2.tar.gz",
            "version": "0.8.2"
        },
```

**Comment by ivankravets** [comment]
Please ping me again here when https://github.com/sipeed/platform-kendryte210/issues/7 will be resolved. We need tool-kflash-kendryte210-v0.8.2.tar.gz with all Python dependencies.

**Comment by ivankravets** [comment]
Done!
