### ISSUE TITLE
Debugging configuration

### ISSUE THREAD

**Issue by ivankravets** [sipeed/platform-kendryte210#9]
I see you added debugging configuration for all boards. Do they really have FTDI + JLink on-board debugging probes?

**Comment by carlosedp** [comment]
I have a similar problem on my Sipeed MaixGo board, while trying to use it with the Kendryte standalone SDK, I can't debug using it's internal link to see registers and instructions.

**Comment by bitsk** [comment]
Maix-go's on-board debugger open-ec is not yet developed, and can only be debugged using external ftdi or jlink.

**Comment by ivankravets** [comment]
@btx000 which boards from this list https://github.com/sipeed/platform-kendryte210/tree/master/boards have on-board debugger(probe) and which are ready for external via JTAG?

**Comment by bitsk** [comment]
> @btx000 which boards from this list https://github.com/sipeed/platform-kendryte210/tree/master/boards have on-board debugger(probe) and which are ready for external via JTAG?

All boards can be debugged using external JTAG，only maix go has an on-board debugger.
